"""Serializers for the stapel-analytics API.

Model-backed response serializers are generated by the presenters
(``stapel_core.django.api.presenters.Presenter``); request serializers and
non-model envelopes live here.

The ingest REQUEST serializer is deliberately loose — ``events`` is a list
of free-form objects and nothing more. Per-event validation happens in
``ingest.normalize_batch``, because DRF's answer to a bad item in a list is
to refuse the whole list, and this endpoint's contract is the opposite:
accept what is valid, name what is not, and never make a retrying offline
buffer choose between twenty events and one.
"""
from __future__ import annotations

from rest_framework import serializers
from stapel_core.django.api.serializers import StapelDataclassSerializer

from .dto import (
    EventRegistry,
    EventsReport,
    FunnelDefinition,
    FunnelReportDTO,
    IngestReceipt,
)
from .presenters import get_funnel_presenter

FunnelSerializer = get_funnel_presenter().serializer_class()


# ── Envelope responses ───────────────────────────────────────────────


class IngestReceiptSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = IngestReceipt


class EventRegistrySerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = EventRegistry


class FunnelDefinitionSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = FunnelDefinition


class FunnelReportSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = FunnelReportDTO


class EventsReportSerializer(StapelDataclassSerializer):
    class Meta:
        dataclass = EventsReport


# ── Requests ─────────────────────────────────────────────────────────


class IngestSerializer(serializers.Serializer):
    """The batch, as ``@stapel/analytics`` sends it.

    ``write_key`` is optional because the shipped facade omits it unless a
    host configured one; ``anon_id`` / ``session_id`` are batch-level
    defaults the current facade does not send at all and a server-side
    producer does. See ``ingest.py`` for the whole wire contract.
    """

    events = serializers.ListField(child=serializers.DictField(), allow_empty=True)
    write_key = serializers.CharField(required=False, allow_blank=True)
    anon_id = serializers.CharField(required=False, allow_blank=True)
    session_id = serializers.CharField(required=False, allow_blank=True)


class FunnelCreateSerializer(serializers.Serializer):
    slug = serializers.SlugField(max_length=100)
    steps = serializers.ListField(child=serializers.CharField(max_length=200))
    title = serializers.CharField(max_length=200, required=False, allow_blank=True)
    description = serializers.CharField(required=False, allow_blank=True)
    window_seconds = serializers.IntegerField(required=False, min_value=1)
    is_active = serializers.BooleanField(required=False, default=True)
    workspace_id = serializers.UUIDField(required=False, allow_null=True)


class FunnelPatchSerializer(serializers.Serializer):
    steps = serializers.ListField(child=serializers.CharField(max_length=200),
                                  required=False)
    title = serializers.CharField(max_length=200, required=False, allow_blank=True)
    description = serializers.CharField(required=False, allow_blank=True)
    window_seconds = serializers.IntegerField(required=False, min_value=1)
    is_active = serializers.BooleanField(required=False)


class ReportQuerySerializer(serializers.Serializer):
    start = serializers.DateTimeField(required=False)
    end = serializers.DateTimeField(required=False)
    compare = serializers.BooleanField(required=False, default=False)


class EventsReportQuerySerializer(serializers.Serializer):
    start = serializers.DateTimeField(required=False)
    end = serializers.DateTimeField(required=False)
    #: Payload keys to group by. ``name`` is the useful default (what was
    #: fired, how often); ``source`` and ``kind`` are the other two a
    #: dashboard asks for.
    group_by = serializers.ListField(
        child=serializers.ChoiceField(choices=["name", "source", "kind"]),
        required=False,
    )


class FunnelListQuerySerializer(serializers.Serializer):
    workspace_id = serializers.UUIDField(required=False, allow_null=True)
    mine = serializers.BooleanField(required=False, default=False)
    #: Bounded by STAPEL_ANALYTICS["MAX_PAGE_SIZE"] — a caller may ask for
    #: less, never for more.
    limit = serializers.IntegerField(required=False, min_value=1)


__all__ = [
    "EventRegistrySerializer",
    "EventsReportQuerySerializer",
    "EventsReportSerializer",
    "FunnelCreateSerializer",
    "FunnelDefinitionSerializer",
    "FunnelListQuerySerializer",
    "FunnelPatchSerializer",
    "FunnelReportSerializer",
    "FunnelSerializer",
    "IngestReceiptSerializer",
    "IngestSerializer",
    "ReportQuerySerializer",
]
