# Generated by Django 6.0.8 on 2026-08-24 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('steps', models.JSONField(default=list)),
                ('window_seconds', models.PositiveIntegerField(default=604800)),
                ('is_active', models.BooleanField(default=True)),
                ('owner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('slug',),
                'indexes': [models.Index(fields=['workspace_id', 'is_active'], name='anl_funnel_ws_idx')],
            },
        ),
    ]
