# Generated by Django 6.0.8 on 2026-09-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_id', models.CharField(max_length=512)),
                ('click_id_type', models.CharField(choices=[('gclid', 'gclid'), ('gbraid', 'gbraid'), ('wbraid', 'wbraid')], default='gclid', max_length=8)),
                ('conversion_action', models.CharField(blank=True, default='', max_length=255)),
                ('conversion_at', models.DateTimeField()),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('uploaded', 'uploaded'), ('rejected', 'rejected'), ('skipped', 'skipped')], db_index=True, default='pending', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='anl_conv_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('click_id', 'conversion_action', 'conversion_at'), name='anl_conv_upload_uniq')],
            },
        ),
    ]
