# Generated by Django 6.0.8 on 2026-09-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_conversionupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionFeedFetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('remote', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ('-at',),
            },
        ),
    ]
