# Generated by Django 6.0.7 on 2026-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_conversionfeedfetch'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(unique=True)),
                ('click_id', models.CharField(max_length=512)),
                ('click_id_type', models.CharField(max_length=8)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('source', models.CharField(default='cookie', max_length=32)),
                ('expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-captured_at',),
                'indexes': [models.Index(fields=['click_id'], name='anl_attr_click_idx')],
            },
        ),
    ]
